import Anita from "./images/Anita.jpg";
import Rohit from "./images/Rohit.jpg";
import Neha from "./images/Neha.jpg";
import Sameer from "./images/Sameer.jpg";
import Priya from "./images/Priya.jpg";
import Karan from "./images/Karan.jpg";
import Sanya from "./images/Sanya.jpg";
import Rajeev from "./images/Rajeev.jpg";
import Tanvi from "./images/Tanvi.jpg";
import Arjun from "./images/Arjun.jpg";
import Isha from "./images/Isha.jpg";
import Dev from "./images/Dev.jpg";
import Meera from "./images/Meera.jpg";
import Kabir from "./images/Kabir.jpg";
import Aisha from "./images/Aisha.jpg";

export const photographers = [
  {
    id: 1,
    name: "Ravi Studio",
    category: "Maternity",
    location: "Bengaluru",
    style: "Studio",
    rating: 4.6,
    price: 10000,
    profileImage: Anita,
    description: "Award-winning studio specializing in maternity and newborn shoots.",
    contact: "ravi.studio@example.com",
  },
  {
    id: 2,
    name: "Lens Queen Photography",
    category: "Birthday",
    location: "Delhi",
    style: "Candid",
    rating: 4.2,
    price: 15000,
    profileImage: Kabir,
    description: "Delhi-based candid specialist for kids and birthday parties.",
    contact: "lensqueen@example.com",
  },
  {
    id: 3,
    name: "Click Factory",
    category: "Wedding",
    location: "Mumbai",
    style: "Traditional",
    rating: 4.8,
    price: 8000,
    profileImage: Priya,
    description: "Capturing timeless wedding stories across India.",
    contact: "clickfactory@example.com",
  },
  {
    id: 4,
    name: "Moments by Neha",
    category: "Maternity",
    location: "Bengaluru",
    style: "Outdoor",
    rating: 4.3,
    price: 12000,
    profileImage: Rohit,
    description: "Natural light specialist focusing on emotional storytelling.",
    contact: "moments.neha@example.com",
  },
  {
    id: 5,
    name: "Snapshot Studio",
    category: "Birthday",
    location: "Hyderabad",
    style: "Studio",
    rating: 3.9,
    price: 7000,
    profileImage: Neha,
    description: "Affordable indoor shoots with creative themes.",
    contact: "snapshot@example.com",
  },
  {
    id: 6,
    name: "Sneha Clicks",
    category: "Maternity",
    location: "Delhi",
    style: "Outdoor",
    rating: 4.7,
    price: 14500,
    profileImage: Sameer,
    description: "Candid maternity photoshoots capturing emotional moments.",
    contact: "sneha@clicks.com",
  },
  {
    id: 7,
    name: "Shutter Souls",
    category: "Birthday",
    location: "Chennai",
    style: "Candid",
    rating: 4.4,
    price: 10500,
    profileImage: Karan,
    description: "Kids birthday specialist with natural expressions and vibrant themes.",
    contact: "shuttersouls@example.com",
  },
  {
    id: 8,
    name: "Frame Factory",
    category: "Wedding",
    location: "Ahmedabad",
    style: "Candid",
    rating: 4.9,
    price: 16000,
    profileImage: Sanya,
    description: "Top-rated wedding photographer with cinematic style.",
    contact: "framefactory@example.com",
  },
  {
    id: 9,
    name: "Baby Bliss Photos",
    category: "Newborn",
    location: "Kolkata",
    style: "Studio",
    rating: 4.6,
    price: 11000,
    profileImage: Rajeev,
    description: "Studio shoots for newborns with safety and creativity.",
    contact: "babybliss@example.com",
  },
  {
    id: 10,
    name: "Glow Snaps",
    category: "Maternity",
    location: "Pune",
    style: "Outdoor",
    rating: 4.8,
    price: 17500,
    profileImage: Tanvi,
    description: "Natural light maternity shoots with elegant themes.",
    contact: "glowsnaps@example.com",
  },
  {
    id: 11,
    name: "Capture Crew",
    category: "Wedding",
    location: "Jaipur",
    style: "Traditional",
    rating: 4.5,
    price: 14000,
    profileImage: Arjun,
    description: "Traditional wedding moments frozen beautifully forever.",
    contact: "capturecrew@example.com",
  },
  {
    id: 12,
    name: "Little Laughs",
    category: "Birthday",
    location: "Surat",
    style: "Studio",
    rating: 4.1,
    price: 9500,
    profileImage: Isha,
    description: "Colorful and joyful studio setups for kids birthdays.",
    contact: "littlelaughs@example.com",
  },
  {
    id: 13,
    name: "Candid Aura",
    category: "Maternity",
    location: "Bhopal",
    style: "Candid",
    rating: 4.6,
    price: 13000,
    profileImage: Dev,
    description: "Maternity portraits with a warm candid feel.",
    contact: "candidaura@example.com",
  },
  {
    id: 14,
    name: "Royal Frames",
    category: "Wedding",
    location: "Lucknow",
    style: "Candid",
    rating: 4.7,
    price: 15500,
    profileImage: Meera,
    description: "Luxury wedding storytelling with flair and emotion.",
    contact: "royalframes@example.com",
  },
  {
    id: 15,
    name: "Tiny Tales Studio",
    category: "Newborn",
    location: "Bengaluru",
    style: "Studio",
    rating: 4.4,
    price: 12000,
    profileImage: Aisha,
    description: "Tiny toes and tiny tales captured with love.",
    contact: "tinytales@example.com",
  },
];
